// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NiftyCoders.Services.TraineeManagement.Persistence;

#nullable disable

namespace NiftyCoders.Services.TraineeManagement.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NiftyCoders.Services.TraineeManagement.Persistence.Entities.Trainee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("TrainningPeriodId")
                        .HasColumnType("int");

                    b.Property<int>("UniversityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainningPeriodId");

                    b.HasIndex("UniversityId");

                    b.ToTable("Trainees", (string)null);
                });

            modelBuilder.Entity("NiftyCoders.Services.TraineeManagement.Persistence.Entities.TrainningPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("TrainningPeriod", (string)null);
                });

            modelBuilder.Entity("NiftyCoders.Services.TraineeManagement.Persistence.Entities.University", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Universities", (string)null);
                });

            modelBuilder.Entity("NiftyCoders.Services.TraineeManagement.Persistence.Entities.Trainee", b =>
                {
                    b.HasOne("NiftyCoders.Services.TraineeManagement.Persistence.Entities.TrainningPeriod", "TrainningPeriod")
                        .WithMany("Trainees")
                        .HasForeignKey("TrainningPeriodId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Trainee_TrainningPeriod_TrainningPeriodId");

                    b.HasOne("NiftyCoders.Services.TraineeManagement.Persistence.Entities.University", "University")
                        .WithMany("Trainees")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Trainee_University_UniversityId");

                    b.Navigation("TrainningPeriod");

                    b.Navigation("University");
                });

            modelBuilder.Entity("NiftyCoders.Services.TraineeManagement.Persistence.Entities.TrainningPeriod", b =>
                {
                    b.Navigation("Trainees");
                });

            modelBuilder.Entity("NiftyCoders.Services.TraineeManagement.Persistence.Entities.University", b =>
                {
                    b.Navigation("Trainees");
                });
#pragma warning restore 612, 618
        }
    }
}
